theme: jekyll-theme-cayman
title: Amigo
description: Papago Client for Mac OS
show_downloads: true
version: 1.0.0
google_analytics: UA-118378824-1
github:
  zip_url: https://drive.google.com/open?id=1OC6f24V6jRdDh46L1U_DrdWqsweyYzqs
